### PR TITLE
Support RN 0.40, change header import path

### PR DESCRIPTION
**Pull request by messense**
iOS native headers moved in RN 0.40

https://github.com/facebook/react-native/releases/tag/v0.40.0

### CODE REVIEW

**Comment by jordanbyron** [comment]
@messense correct me if I am wrong, but this will be a breaking change and force us to only support RN 0.40 and up?

**Comment by messense** [comment]
Yes, it's a breaking changing that requires a major version bump.

**Comment by messense** [comment]
Sadly RN developers didn't want to merge [this PR](https://github.com/facebook/react-native/pull/11614) which prevents the breaking change.

**Comment by jordanbyron** [comment]
Gotcha. Thanks for the quick response. Any chance you can also update the README to highlight the breaking change and point towards our current version (0.1.5) as a working version for RN < 0.40.

**Comment by jordanbyron** [comment]
@messense thanks for this!

**Pull request merged**
